import java_cup.runtime.*;
import java.util.*;

init with {:
    objHash = new HashMap();
:};

parser code {:
    public static HashMap objHash;
:};


terminal STAR, EQUAL,SPACE,NEWLINE;
terminal String STRING, URL;

non terminal file,italico1;

start with file;

file ::=italico1 {:
	System.out.printf("Grammar ok\n");	
:};

italico1 ::= STAR STRING:s STAR
{: System.out.printf("Rule Italico1 found\n"); :}
;