
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 01 18:53:53 CEST 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LITCHAR = 10;
  public static final int EQUAL = 4;
  public static final int STAR = 2;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int URL = 9;
  public static final int error = 1;
  public static final int SPACE = 5;
  public static final int NEWLINE = 6;
  public static final int UNDERSCORE = 7;
  public static final int STARDOUBLE = 3;
}

